### PR TITLE
fixed featured channel thumbnails

### PR DESCRIPTION
**Pull request by ChunkyProgrammer**
Related:
https://github.com/FreeTubeApp/FreeTube/pull/1323
closes https://github.com/FreeTubeApp/FreeTube/issues/1322
closes https://github.com/FreeTubeApp/FreeTube/issues/1354

### CODE REVIEW

**Comment by GilgusMaximus** [comment]
I am not too sure, this one is actually required. I need to do some testing, as the channel icons do load when running FT in dev mode.

**Comment by ChunkyProgrammer** [comment]
Interesting, in dev mode it is definitely working better.
## Dev
For Linus Tech Tips, all of the featured icons do load.

image

For Techlore, only half of them do
image

## Prod

None load for Linus Tech Tips

image

And none load for Techlore

image

**Comment by GilgusMaximus** [comment]
yep, so that is the golden question of why does this work in dev but not in production...
I'll checkout your pr and test making production builds . But might take a bit as I am busy with other things atm

**Comment by ChunkyProgrammer** [comment]
Just an update:
It looks like a similar problem occurred with searching channels in FreeTube (I noticed this while working on this pr: [#1477](https://github.com/FreeTubeApp/FreeTube/pull/1477))

[ft-list-channel.js#L49](https://github.com/FreeTubeApp/FreeTube/blob/development/src/renderer/components/ft-list-channel/ft-list-channel.js#L49)

If adding an if to check if there's https or not in freetube instead of here would be a better option lmk

**Comment by GilgusMaximus** [comment]
I think adding it to Freetube would be the better option.
This is not module related but FreeTube related. And we do not want to add more logic than needed for other users :)

Thanks for finding that !

Best Regards,
Gilgus

**Pull request closed without merging**
